dist: trusty
sudo: required

language: node_js
node_js:
  - "10"

matrix:
  include:
    - os: linux
    - os: osx
    - os: windows

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn lint
  - yarn build
  - yarn release

branches:
  only:
    - master
