dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: linux
      install:
        - sudo apt-get install --no-install-recommends -y libopenjp2-tools
        - sudo apt-get install --no-install-recommends -y gcc-multilib g++-multilib
        - sudo apt-get install --no-install-recommends -y rpm
    - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run release

branches:
  only:
    - master
