language: node_js
node_js:
  - "node"

dist: trusty
sudo: required

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

before_deploy:
  - zip -o -r ./dingtalk-x86_64.zip ./dist/*

deploy:
  provider: releases
  api_key:
    secure: "${token}"
  file:
    - "dingtalk-x86_64.zip"
  skip_cleanup: true
  on:
    branches: master

branches:
  only:
    - master
