language: node_js
node_js:
  - "node"

dist: trusty
sudo: required

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branches: release

branches:
  only:
    - release
