dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: linux
    - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm run release

branches:
  only:
  - master
