dist: trusty
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      language: node_js
      node_js:
        - "node"

    - os: linux
      language: node_js
      node_js:
        - "node"

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - echo $TRAVIS_OS_NAME
  - ls

script:
  - npm run build
  - ls
  - cd release && ls
  - npm run dist

deploy:
  provider: github
  script: npm run deploy
  skip_cleanup: true
  on:
    branches:
      except:
        - "/^release \\d+\\.\\d+\\.\\d+$/"

branches:
  except:
    - "/^release \\d+\\.\\d+\\.\\d+$/"
