dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: linux
    - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run release
  - cd release
  - ls
  - cat latest.yml

branches:
  only:
  - dev
