dist: trusty
sudo: required

language: node_js
node_js:
  - "node"

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
          - libopenjp2-tools
          - gcc-multilib
          - g++-multilib
          - rpm
    - os: osx

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run lint
  - npm run build
  - npm run release

branches:
  only:
    - master
