language: node_js
node_js:
  - "node"

dist: trusty
sudo: required

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build

deploy:
  script:
    - scripts/release.js
  skip_cleanup: true
  on:
    branches: master

branches:
  only:
    - master
